# Generated by Django 5.1.1 on 2024-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('company', models.TextField()),
                ('job_link', models.URLField(max_length=1000)),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('scraped_for', models.CharField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
