# Generated by Django 5.1.1 on 2024-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='required_skills',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='suggested_job_role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
