# Generated by Django 5.1.1 on 2025-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingModule', '0003_remove_resume_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('skills', models.JSONField()),
                ('rating', models.FloatField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
