# Generated by Django 5.1.1 on 2025-02-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingModule', '0004_courselistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselistings',
            name='scraped_for',
            field=models.CharField(default='trending'),
        ),
    ]
